# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.zsh-custom

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME=powerlevel10k/powerlevel10k
export EDITOR=vim

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want disable red dots displayed while waiting for completion
# DISABLE_COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)

plugins=(gitfast git brew zoxide tmux virtualenv zsh-vim-mode fzf)
export CLICOLOR=1
source $ZSH/oh-my-zsh.sh
for ve in rbenv pyenv; do
    if type ${ve} &> /dev/null; then
        eval "$(${ve} init -)"
    fi
done
source ~/.zsh_aliases
command -v brew >/dev/null 2>&1 && fpath=($fpath $(brew --prefix)/share/zsh-completions)

setopt interactive_comments
setopt dotglob

fpath=($HOME/.zsh/func $fpath)
typeset -U fpath
export PAGER=less
mcd() { mkdir -p "$@" && cd "$_"; }
# Ignore pyc and backup files when tab completing
zstyle ':completion:*:(all-|)files' ignored-patterns "(*.pyc|*~)"
export PYTHONSTARTUP=$HOME/.pythonrc.py

GPG_TTY=`tty`
export GPG_TTY

function update_repo() {
        (cd $1 && git pull)
}
if which aactivator >/dev/null 2>&1; then
    eval "$(aactivator init)"
fi
typeset -U path

function gi() { curl -sLw n https://www.gitignore.io/api/$@ ;}
function clean_aws_vars() {
  env | grep aws -i | awk -F= '{print $1}' | while read var; do unset $var; done
}

if [[ -n $TMUX ]]; then
  export NVIM_LISTEN_ADDRESS=${HOME}/tmp/socket/nvim_$(tmux display -p "#{window_id}")
fi

export LESS="--quit-if-one-screen --ignore-case --status-column --LONG-PROMPT --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --no-init --window=-4"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
type kubectl > /dev/null && source <(kubectl completion zsh)

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

compdef diff delta
autoload -U compinit && compinit

export GOPATH=~/.go
[[ ! -f ~/.zshenv_local ]] || source ~/.zshenv_local
path=("${KREW_ROOT:-$HOME/.krew}/bin" "$HOME/.npm-prefix/bin" "$HOME/.local/bin" "$GOPATH/bin" "$HOME/bin" "/usr/local/sbin" "/usr/local/bin" $path)
# export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$HOME/.local/bin:$GOPATH/bin:$HOME/bin:/usr/local/sbin:/usr/local/bin:$PATH"
export PATH
test -e "${HOME}/.ripgreprc" && export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"
test -e "${HOME}/.zsh_local" && source "${HOME}/.zsh_local"
eval "$(direnv hook zsh)"
