---
- name: Git Repos
  git: repo={{ item.repo }} dest={{ item.dest }}
  with_items: dotfiles.timmow.git.repos
  tags: dotfiles
- name: dotfile repos symlinks
  file: src={{ item.src }} dest={{ item.dst }} state=link
  with_items: dotfiles.timmow.symlinks
- name: tmp_dir
  file: path="{{ timmow.home }}/tmp" state=directory
- name: vagrant_dir
  file: path="{{ timmow.home }}/.vagrant.d" state=directory
- name: link dotfiles
  file: src={{ item }} dest={{timmow.home}}/.{{ item | basename }} state=link
  with_fileglob:
    - ./simple/*
  tags: dotfiles

- name: git config template
  template: src="gitconfig" dest={{timmow.home}}/.gitconfig
