---
- name: Git Repos
  git: repo={{ item.repo }} dest={{ item.dest }}
  with_items: dotfiles.timmow.git.repos
  tags: dotfiles
- name: symlinks
  file: src={{ item.src }} dest={{ item.dst }} state=link
  with_items: dotfiles.timmow.symlinks
- name: tmp_dir
  file: path="{{ timmow.home }}/tmp" state=directory

