---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
- name: install packages
  apt: name={{ item }}
  with_items: 
    - git
    - zsh
    - ack-grep
    - mercurial
  sudo: yes
