VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "#{ENV['HOME']}/src/ansible/site.yml"
    ansible.verbose = 'vvv'
  end
end
