VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.forward_agent = true
  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
    # v.gui = true
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "#{ENV['HOME']}/src/ansible/site.yml"
    ansible.verbose = 'vvv'
  end
  config.vm.provision "shell", inline: "sudo chsh -s /bin/zsh vagrant"
  config.vm.provision "shell", inline: "echo 'vagrant' > /home/vagrant/.box_name"
end
