# file: group_vars/dotfile_repos.yaml
---
dotfiles:
  timmow:
    git:
      repos:
        - name: vimrc
          repo: "git://github.com/timmow/vimrc.git"
          dest: "~/.vimfiles"
        - name: slaterc
          repo: "git://github.com/timmow/slaterc.git"
          dest: "~/.slaterc"
        - name: ohmyzsh
          repo: "git://github.com/robbyrussell/oh-my-zsh.git"
          dest: "~/.oh-my-zsh"
        - name: ansible
          repo: "git://github.com/timmow/ansible.git"
          dest: "~/src/ansible"
        - name: tpm
          repo: "https://github.com/tmux-plugins/tpm"
          dest: "~/.tmux/plugins/tpm"
        - name: fasd
          repo: "https://github.com/clvv/fasd"
          dest: "~/src/fasd"
        - name: p10k
          repo: "https://github.com/romkatv/powerlevel10k"
          dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
    symlinks:
      - src: "~/.vimfiles/_vimrc"
        dst: "~/.vimrc"
      - src: "~/.vimfiles/vimfiles"
        dst: "~/.vim"
      - src: "~/.slaterc/home/.slate"
        dst: "~/.slate"
      - src: "~/src/ansible/roles/dotfiles/files/Vagrantfile"
        dst: "~/.vagrant.d/Vagrantfile"
